// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/email-workspace/Current.tsx": () => import("../components/mockups/email-workspace/Current.tsx"),
  "./components/mockups/email-workspace/Overhaul.tsx": () => import("../components/mockups/email-workspace/Overhaul.tsx")
};
